version: "3.6"

services:
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=notemaker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres_data:
